eureka: 
   client:
      register-with-eureka: true
      fetch-registry: true 
      serviceUrl: 
         #defaultZone: http://7fb6b1eda5c4445eaf6a.eastus.aksapp.io/eureka 
         defaultZone: http://localhost:8081/eureka
   instance:
      hostname: localhost
spring:
  application:
    name: search
server:
   port: 9595
   